spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/zhihaomiao/config-repo-demo
          username: zhihao.miao
          password: 13579qwertyu
          search-paths: config-repo
server:
  port: 9090